"""
Dump SQLite Schema
==================
Reads all tables, views, and indexes from a SQLite database and writes
their DDL statements to a .sql file.

Usage:
    python dump_schema.py [--db weather.db] [--out schema.sql]
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

DEFAULT_DB = "weather.db"
DEFAULT_OUT = "schema.sql"


def dump_schema(db_path: str, out_path: str) -> None:
    """Export the full DDL from *db_path* to *out_path*."""
    conn = sqlite3.connect(db_path)
    cursor = conn.execute(
        "SELECT type, name, sql FROM sqlite_master "
        "WHERE sql IS NOT NULL ORDER BY type, name"
    )

    sections: dict[str, list[str]] = {
        "table": [],
        "view": [],
        "index": [],
        "trigger": [],
    }

    for obj_type, name, sql in cursor:
        sections.setdefault(obj_type, []).append(sql + ";")

    conn.close()

    lines: list[str] = [
        "-- =============================================================",
        "-- Telia Weather ETL — Database Schema",
        "-- Auto-generated by dump_schema.py",
        "-- =============================================================",
        "",
    ]

    section_labels = {
        "table": "Tables",
        "view": "Views",
        "index": "Indexes",
        "trigger": "Triggers",
    }

    for key in ("table", "view", "index", "trigger"):
        stmts = sections.get(key, [])
        if not stmts:
            continue
        lines.append(f"-- ------- {section_labels[key]} -------")
        lines.append("")
        for stmt in stmts:
            lines.append(stmt)
            lines.append("")

    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"Schema written to {out_path}")


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Export SQLite schema to SQL file")
    parser.add_argument("--db", default=DEFAULT_DB, help="SQLite database path")
    parser.add_argument("--out", default=DEFAULT_OUT, help="Output .sql file path")
    args = parser.parse_args()
    dump_schema(args.db, args.out)


if __name__ == "__main__":
    main()
